services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm start

  backend:
    build: ./backend/django
    ports:
      - "8000:8000"
    volumes:
      - ./backend/django:/app
    working_dir: /app
    command: >
      sh -c "python manage.py runserver 8000"

  fastapi:
    build: ./backend/fastapi
    ports:
      - "9000:9000"
    volumes:
      - ./backend/fastapi:/app
      - ./backend/django:/app/django  # Django 프로젝트 공유
    working_dir: /app
    command: >
      sh -c "uvicorn main:app --port 9000 --reload"
    environment:
      - ENV=development