services:
  django:
    platform: linux/amd64        # Mac M1 대응
    build:
      context: ./backend/django_app
    ports:
      - "8000:8000"
    volumes:
      - ./backend/django_app:/app
    working_dir: /app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./backend/django_app/.env
    container_name: django_app

  fastapi:
    platform: linux/amd64        # Mac M1 대응
    build:
      context: ./backend/fastapi_app
    ports:
      - "9000:9000"
    volumes:
      - ./backend/fastapi_app:/app
      - ./backend/django_app:/app/django_app
    working_dir: /app
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 9000 --reload"
    env_file:
      - ./backend/fastapi_app/.env
    depends_on:
      - django
    container_name: fastapi_app

  frontend:
    platform: linux/amd64        # Mac M1 대응
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm start
