services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm start

  backend:
    build: ./backend/django_app
    ports:
      - "8000:8000"
    volumes:
      - ./backend/django_app:/app
    working_dir: /app
    command: >
      sh -c "python manage.py runserver 8000"

  fastapi:
    build: ./backend/fastapi_app
    ports:
      - "9000:9000"
    volumes:
      - ./backend/fastapi_app:/app
      - ./backend/django_app:/app/django_app  # Django 프로젝트 공유
    working_dir: /app
    command: >
      sh -c "uvicorn main:app --port 9000 --reload"
    environment:
      - ENV=development