# Generated by Django 5.2.4 on 2025-11-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='label_en',
            field=models.CharField(default='', help_text='표시 이름', max_length=50, verbose_name='영어 메뉴명'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='label_zh',
            field=models.CharField(default='', help_text='표시 이름', max_length=50, verbose_name='중국 메뉴명'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='label',
            field=models.CharField(help_text='표시 이름', max_length=50, verbose_name='한국 메뉴명'),
        ),
    ]
