# Generated by Django 5.2.4 on 2025-11-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_menuitem_label_en_menuitem_label_zh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='external_url',
            field=models.URLField(blank=True, default='', verbose_name='외부 링크 URL'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='path',
            field=models.CharField(blank=True, default='', help_text='내부경로, 그룹타입은 비움(그룹명에만 쓰이고 path가 없어서)', max_length=200, verbose_name='경로'),
        ),
    ]
