# Generated by Django 5.2.4 on 2025-11-05 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_alter_menuitem_external_url_alter_menuitem_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='label',
            new_name='label_kr',
        ),
    ]
