# Generated by Django 5.2.4 on 2025-11-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_rename_label_menuitem_label_kr'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='menuitem',
            name='uniq_menu_root_label',
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('label_kr',), name='uniq_menu_root_label'),
        ),
    ]
