# Generated by Django 5.2.4 on 2025-11-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_remove_menuitem_uniq_menu_root_label_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='menuitem',
            name='uniq_menu_parent_label',
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.UniqueConstraint(fields=('parent', 'label_kr'), name='uniq_menu_parent_label'),
        ),
    ]
