# Generated by Django 5.2.4 on 2025-11-06 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0006_remove_menuitem_uniq_menu_parent_label_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='label_kr',
            new_name='label_ko',
        ),
    ]
