# Generated by Django 5.2.4 on 2025-11-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0007_rename_label_kr_menuitem_label_ko'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='menuitem',
            name='uniq_menu_root_label',
        ),
        migrations.RemoveConstraint(
            model_name='menuitem',
            name='uniq_menu_parent_label',
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.UniqueConstraint(fields=('parent', 'label_ko'), name='uniq_menu_parent_label'),
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('label_ko',), name='uniq_menu_root_label'),
        ),
    ]
